### ISSUE TITLE
identifiers' type information

### ISSUE THREAD

**Issue by antonio-mastropaolo** [LiuFang816/CugLM#1]
Hi,

I was wondering which tool did you use for extracting the identifiers' type information.
Is an open-source one that you can share with me?

Thanks for your help.

**Comment by LiuFang816** [comment]
Hi, for TypeScript programs, we apply the approach in Hellendoorn et al. ("Deep learning type inference, https://github.com/DeepTyper/DeepTyper") to extract type annotations of the identifiers. For Java dataset, we use the service provided by aiXcoder (https://www.aixcoder.com/) to extract the type information.
